namespace JMW.Agent.Common.Models;

public static class InterfaceTypeLookups
{
    public static readonly Dictionary<int, (string, string)> IanaInterfaceType = new()
    {
        { 1, ("Other", "Unknown: None of the following")},
        { 2, ("Regular1822", "")},
        { 3, ("Hdh1822", "")},
        { 4, ("DdnX25", "")},
        { 5, ("Rfc877x25", "")},
        { 6, ("EthernetCsmacd", "For all ethernet-like interfaces, regardless of speed, as per RFC3635")},
        { 7, ("Iso88023Csmacd", "Deprecated via RFC3635 ethernetCsmacd (6) should be used instead")},
        { 8, ("Iso88024TokenBus", "")},
        { 9, ("Iso88025TokenRing", "")},
        { 10, ("Iso88026Man", "")},
        { 11, ("StarLan", "Deprecated via RFC3635 ethernetCsmacd (6) should be used instead")},
        { 12, ("Proteon10Mbit", "")},
        { 13, ("Proteon80Mbit", "")},
        { 14, ("Hyperchannel", "")},
        { 15, ("Fddi", "")},
        { 16, ("Lapb", "")},
        { 17, ("Sdlc", "")},
        { 18, ("Ds1", "DS1-MIB")},
        { 19, ("E1", "Obsolete see DS1-MIB")},
        { 20, ("BasicISDN", "No longer used see also RFC2127")},
        { 21, ("PrimaryISDN", "No longer used see also RFC2127")},
        { 22, ("PropPointToPointSerial", "Proprietary serial")},
        { 23, ("Ppp", "")},
        { 24, ("SoftwareLoopback", "")},
        { 25, ("Eon", "CLNP over IP")},
        { 26, ("Ethernet3Mbit", "")},
        { 27, ("Nsip", "XNS over IP")},
        { 28, ("Slip", "generic SLIP")},
        { 29, ("Ultra", "ULTRA technologies")},
        { 30, ("Ds3", "DS3-MIB")},
        { 31, ("Sip", "SMDS, coffee")},
        { 32, ("FrameRelay", "DTE only.")},
        { 33, ("Rs232", "")},
        { 34, ("Para", "parallel-port")},
        { 35, ("Arcnet", "arcnet")},
        { 36, ("ArcnetPlus", "arcnet plus")},
        { 37, ("Atm", "ATM cells")},
        { 38, ("Miox25", "")},
        { 39, ("Sonet", "SONET or SDH")},
        { 40, ("X25ple", "")},
        { 41, ("Iso88022llc", "")},
        { 42, ("LocalTalk", "")},
        { 43, ("SmdsDxi", "")},
        { 44, ("FrameRelayService", "FRNETSERV-MIB")},
        { 45, ("V35", "")},
        { 46, ("Hssi", "")},
        { 47, ("Hippi", "")},
        { 48, ("Modem", "Generic modem")},
        { 49, ("Aal5", "AAL5 over ATM")},
        { 50, ("SonetPath", "")},
        { 51, ("SonetVT", "")},
        { 52, ("SmdsIcip", "SMDS InterCarrier Interface")},
        { 53, ("PropVirtual", "proprietary virtual/internal")},
        { 54, ("PropMultiplexor", "proprietary multiplexing")},
        { 55, ("Ieee80212", "100BaseVG")},
        { 56, ("FibreChannel", "Fibre Channel")},
        { 57, ("HippiInterface", "HIPPI interfaces")},
        { 58, ("FrameRelayInterconnect", "Obsolete, use either frameRelay(32) or frameRelayService(44).")},
        { 59, ("Aflane8023", "ATM Emulated LAN for 802.3")},
        { 60, ("Aflane8025", "ATM Emulated LAN for 802.5")},
        { 61, ("CctEmul", "ATM Emulated circuit")},
        { 62, ("FastEther", "Obsoleted via RFC3635 ethernetCsmacd (6) should be used instead")},
        { 63, ("Isdn", "ISDN and X.25")},
        { 64, ("V11", "CCITT V.11/X.21")},
        { 65, ("V36", "CCITT V.36")},
        { 66, ("G703at64k", "CCITT G703 at 64Kbps")},
        { 67, ("G703at2mb", "Obsolete see DS1-MIB")},
        { 68, ("Qllc", "SNA QLLC")},
        { 69, ("FastEtherFX", "Obsoleted via RFC3635 ethernetCsmacd (6) should be used instead")},
        { 70, ("Channel", "Channel")},
        { 71, ("Ieee80211", "Radio spread spectrum")},
        { 72, ("Ibm370parChan", "IBM System 360/370 OEMI Channel")},
        { 73, ("Escon", "IBM Enterprise Systems Connection")},
        { 74, ("Dlsw", "Data Link Switching")},
        { 75, ("Isdns", "ISDN S/T interface")},
        { 76, ("Isdnu", "ISDN U interface")},
        { 77, ("Lapd", "Link Access Protocol D")},
        { 78, ("IpSwitch", "IP Switching Objects")},
        { 79, ("Rsrb", "Remote Source Route Bridging")},
        { 80, ("AtmLogical", "ATM Logical Port")},
        { 81, ("Ds0", "Digital Signal Level 0")},
        { 82, ("Ds0Bundle", "Group of ds0s on the same ds1")},
        { 83, ("Bsc", "Bisynchronous Protocol")},
        { 84, ("Async", "Asynchronous Protocol")},
        { 85, ("Cnr", "Combat Net Radio")},
        { 86, ("Iso88025Dtr", "ISO 802.5r DTR")},
        { 87, ("Eplrs", "Ext Pos Loc Report Sys")},
        { 88, ("Arap", "Appletalk Remote Access Protocol")},
        { 89, ("PropCnls", "Proprietary Connectionless Protocol")},
        { 90, ("HostPad", "CCITT-ITU X.29 PAD Protocol")},
        { 91, ("TermPad", "CCITT-ITU X.3 PAD Facility")},
        { 92, ("FrameRelayMPI", "Multiproto Interconnect over FR")},
        { 93, ("X213", "CCITT-ITU X213")},
        { 94, ("Adsl", "Asymmetric Digital Subscriber Loop")},
        { 95, ("Radsl", "Rate-Adapt. Digital Subscriber Loop")},
        { 96, ("Sdsl", "Symmetric Digital Subscriber Loop")},
        { 97, ("Vdsl", "Very H-Speed Digital Subscrib. Loop")},
        { 98, ("Iso88025CRFPInt", "ISO 802.5 CRFP")},
        { 99, ("Myrinet", "Myricom Myrinet")},
        { 100, ("VoiceEM", "Voice recEive and transMit")},
        { 101, ("VoiceFXO", "Voice Foreign Exchange Office")},
        { 102, ("VoiceFXS", "Voice Foreign Exchange Station")},
        { 103, ("VoiceEncap", "Voice encapsulation")},
        { 104, ("VoiceOverIp", "Voice over IP encapsulation")},
        { 105, ("AtmDxi", "ATM DXI")},
        { 106, ("AtmFuni", "ATM FUNI")},
        { 107, ("AtmIma", "ATM IMA")},
        { 108, ("PppMultilinkBundle", "PPP Multilink Bundle")},
        { 109, ("IpOverCdlc", "IBM ipOverCdlc")},
        { 110, ("IpOverClaw", "IBM Common Link Access to Workstn")},
        { 111, ("StackToStack", "IBM stackToStack")},
        { 112, ("VirtualIpAddress", "IBM VIPA")},
        { 113, ("Mpc", "IBM multi-protocol channel support")},
        { 114, ("IpOverAtm", "IBM ipOverAtm")},
        { 115, ("Iso88025Fiber", "ISO 802.5j Fiber Token Ring")},
        { 116, ("Tdlc", "IBM twinaxial data link control")},
        { 117, ("GigabitEthernet", "Obsoleted via RFC3635 ethernetCsmacd (6) should be used instead")},
        { 118, ("Hdlc", "HDLC")},
        { 119, ("Lapf", "LAP F")},
        { 120, ("V37", "V.37")},
        { 121, ("X25mlp", "Multi-Link Protocol")},
        { 122, ("X25huntGroup", "X25 Hunt Group")},
        { 123, ("TranspHdlc", "Transp HDLC")},
        { 124, ("Interleave", "Interleave channel")},
        { 125, ("Fast", "Fast channel")},
        { 126, ("Ip", "IP (for APPN HPR in IP networks)")},
        { 127, ("DocsCableMaclayer", "CATV Mac Layer")},
        { 128, ("DocsCableDownstream", "CATV Downstream interface")},
        { 129, ("DocsCableUpstream", "CATV Upstream interface")},
        { 130, ("A12MppSwitch", "Avalon Parallel Processor")},
        { 131, ("Tunnel", "Encapsulation interface")},
        { 132, ("Coffee", "Coffee pot")},
        { 133, ("Ces", "Circuit Emulation Service")},
        { 134, ("AtmSubInterface", "ATM Sub Interface")},
        { 135, ("L2vlan", "Layer 2 Virtual LAN using 802.1Q")},
        { 136, ("L3ipvlan", "Layer 3 Virtual LAN using IP")},
        { 137, ("L3ipxvlan", "Layer 3 Virtual LAN using IPX")},
        { 138, ("DigitalPowerline", "IP over Power Lines")},
        { 139, ("MediaMailOverIp", "Multimedia Mail over IP")},
        { 140, ("Dtm", "Dynamic syncronous Transfer Mode")},
        { 141, ("Dcn", "Data Communications Network")},
        { 142, ("IpForward", "IP Forwarding Interface")},
        { 143, ("Msdsl", "Multi-rate Symmetric DSL")},
        { 144, ("Ieee1394", "IEEE1394 High Performance Serial Bus")},
        { 145, ("IfGsn", "HIPPI-6400")},
        { 146, ("DvbRccMacLayer", "DVB-RCC MAC Layer")},
        { 147, ("DvbRccDownstream", "DVB-RCC Downstream Channel")},
        { 148, ("DvbRccUpstream", "DVB-RCC Upstream Channel")},
        { 149, ("AtmVirtual", "ATM Virtual Interface")},
        { 150, ("MplsTunnel", "MPLS Tunnel Virtual Interface")},
        { 151, ("Srp", "Spatial Reuse Protocol")},
        { 152, ("VoiceOverAtm", "Voice Over ATM")},
        { 153, ("VoiceOverFrameRelay", "Voice Over Frame Relay")},
        { 154, ("Idsl", "	Digital Subscriber Loop over ISDN")},
        { 155, ("CompositeLink", "Avici Composite Link Interface")},
        { 156, ("Ss7SigLink", "SS7 Signaling Link")},
        { 157, ("PropWirelessP2P", "Prop. P2P wireless interface")},
        { 158, ("FrForward", "Frame Forward Interface")},
        { 159, ("Rfc1483", "Multiprotocol over ATM AAL5")},
        { 160, ("Usb", "USB Interface")},
        { 161, ("Ieee8023adLag", "IEEE 802.3ad Link Aggregate")},
        { 162, ("Bgppolicyaccounting", "BGP Policy Accounting")},
        { 163, ("Frf16MfrBundle", "FRF .16 Multilink Frame Relay")},
        { 164, ("H323Gatekeeper", "H323 Gatekeeper")},
        { 165, ("H323Proxy", "H323 Voice and Video Proxy")},
        { 166, ("Mpls", "MPLS")},
        { 167, ("MfSigLink", "Multi-frequency signaling link")},
        { 168, ("Hdsl2", "High Bit-Rate DSL - 2nd generation")},
        { 169, ("Shdsl", "Multirate HDSL2")},
        { 170, ("Ds1FDL", "Facility Data Link 4Kbps on a DS1")},
        { 171, ("Pos", "Packet over SONET/SDH Interface")},
        { 172, ("DvbAsiIn", "DVB-ASI Input")},
        { 173, ("DvbAsiOut", "DVB-ASI Output")},
        { 174, ("Plc", "Power Line Communtications")},
        { 175, ("Nfas", "Non Facility Associated Signaling")},
        { 176, ("Tr008", "TR008")},
        { 177, ("Gr303RDT", "Remote Digital Terminal")},
        { 178, ("Gr303IDT", "Integrated Digital Terminal")},
        { 179, ("Isup", "ISUP")},
        { 180, ("PropDocsWirelessMaclayer", "Cisco proprietary Maclayer")},
        { 181, ("PropDocsWirelessDownstream", "Cisco proprietary Downstream")},
        { 182, ("PropDocsWirelessUpstream", "Cisco proprietary Upstream")},
        { 183, ("Hiperlan2", "HIPERLAN Type 2 Radio Interface")},
        { 184, ("PropBWAp2Mp", "PropBroadbandWirelessAccesspt2multipt use of this iftype for IEEE 802.16 WMAN interfaces as per IEEE Std 802.16f is deprecated and ifType 237 should be used instead.")},
        { 185, ("SonetOverheadChannel", "SONET Overhead Channel")},
        { 186, ("DigitalWrapperOverheadChannel", "Digital Wrapper")},
        { 187, ("Aal2", "ATM adaptation layer 2")},
        { 188, ("RadioMAC", "MAC layer over radio links")},
        { 189, ("AtmRadio", "ATM over radio links")},
        { 190, ("Imt", "Inter Machine Trunks")},
        { 191, ("Mvl", "Multiple Virtual Lines DSL")},
        { 192, ("ReachDSL", "Long Reach DSL")},
        { 193, ("FrDlciEndPt", "Frame Relay DLCI End Point")},
        { 194, ("AtmVciEndPt", "ATM VCI End Point")},
        { 195, ("OpticalChannel", "Optical Channel")},
        { 196, ("OpticalTransport", "Optical Transport")},
        { 197, ("PropAtm", "Proprietary ATM")},
        { 198, ("VoiceOverCable", "Voice Over Cable Interface")},
        { 199, ("Infiniband", "Infiniband")},
        { 200, ("TeLink", "TE Link")},
        { 201, ("Q2931", "Q.2931")},
        { 202, ("VirtualTg", "Virtual Trunk Group")},
        { 203, ("SipTg", "SIP Trunk Group")},
        { 204, ("SipSig", "SIP Signaling")},
        { 205, ("DocsCableUpstreamChannel", "CATV Upstream Channel")},
        { 206, ("Econet", "Acorn Econet")},
        { 207, ("Pon155", "FSAN 155Mb Symetrical PON interface")},
        { 208, ("Pon622", "FSAN622Mb Symetrical PON interface")},
        { 209, ("Bridge", "Transparent bridge interface")},
        { 210, ("Linegroup", "Interface common to multiple lines")},
        { 211, ("VoiceEMFGD", "Voice E&M Feature Group D")},
        { 212, ("VoiceFGDEANA", "Voice FGD Exchange Access North American")},
        { 213, ("VoiceDID", "Voice Direct Inward Dialing")},
        { 214, ("MpegTransport", "MPEG transport interface")},
        { 215, ("SixToFour", "6to4 interface (DEPRECATED)")},
        { 216, ("Gtp", "GTP (GPRS Tunneling Protocol)")},
        { 217, ("PdnEtherLoop1", "Paradyne EtherLoop 1")},
        { 218, ("PdnEtherLoop2", "Paradyne EtherLoop 2")},
        { 219, ("OpticalChannelGroup", "Optical Channel Group")},
        { 220, ("Homepna", "HomePNA ITU-T G.989")},
        { 221, ("Gfp", "Generic Framing Procedure (GFP)")},
        { 222, ("CiscoISLvlan", "Layer 2 Virtual LAN using Cisco ISL")},
        { 223, ("ActelisMetaLOOP", "Acteleis proprietary MetaLOOP High Speed Link")},
        { 224, ("FcipLink", "FCIP Link")},
        { 225, ("Rpr", "Resilient Packet Ring Interface Type")},
        { 226, ("Qam", "RF Qam Interface")},
        { 227, ("Lmp", "Link Management Protocol")},
        { 228, ("CblVectaStar", "Cambridge Broadband Networks Limited VectaStar")},
        { 229, ("DocsCableMCmtsDownstream", "CATV Modular CMTS Downstream Interface")},
        { 230, ("Adsl2", "Asymmetric Digital Subscriber Loop Version 2 (DEPRECATED/OBSOLETED - please use adsl2plus 238 instead)")},
        { 231, ("MacSecControlledIF", "MACSecControlled")},
        { 232, ("MacSecUncontrolledIF", "MACSecUncontrolled")},
        { 233, ("AviciOpticalEther", "Avici Optical Ethernet Aggregate")},
        { 234, ("Atmbond", "atmbond")},
        { 235, ("VoiceFGDOS", "Voice FGD Operator Services")},
        { 236, ("MocaVersion1", "MultiMedia over Coax Alliance (MoCA) Interface as documented in information provided privately to IANA")},
        { 237, ("Ieee80216WMAN", "IEEE 802.16 WMAN interface")},
        { 238, ("Adsl2plus", "Asymmetric Digital Subscriber Loop Version 2, Version 2 Plus and all variants")},
        { 239, ("DvbRcsMacLayer", "DVB-RCS MAC Layer")},
        { 240, ("DvbTdm", "DVB Satellite TDM")},
        { 241, ("DvbRcsTdma", "DVB-RCS TDMA")},
        { 242, ("X86Laps", "LAPS based on ITU-T X.86/Y.1323")},
        { 243, ("WwanPP", "3GPP WWAN")},
        { 244, ("WwanPP2", "3GPP2 WWAN")},
        { 245, ("VoiceEBS", "Voice P-phone EBS physical interface")},
        { 246, ("IfPwType", "Pseudowire interface type")},
        { 247, ("Ilan", "Internal LAN on a bridge per IEEE 802.1ap")},
        { 248, ("Pip", "Provider Instance Port on a bridge per IEEE 802.1ah PBB")},
        { 249, ("AluELP", "Alcatel-Lucent Ethernet Link Protection")},
        { 250, ("Gpon", "Gigabit-capable passive optical networks (G-PON) as per ITU-T G.984")},
        { 251, ("Vdsl2", "Very high speed digital subscriber line Version 2 (as per ITU-T Recommendation G.993.2)")},
        { 252, ("CapwapDot11Profile", "WLAN Profile Interface")},
        { 253, ("CapwapDot11Bss", "WLAN BSS Interface")},
        { 254, ("CapwapWtpVirtualRadio", "WTP Virtual Radio Interface")},
        { 255, ("Bits", "Bitsport")},
        { 256, ("DocsCableUpstreamRfPort", "DOCSIS CATV Upstream RF Port")},
        { 257, ("CableDownstreamRfPort", "CATV downstream RF port")},
        { 258, ("VmwareVirtualNic", "VMware Virtual Network Interface")},
        { 259, ("Ieee802154", "IEEE 802.15.4 WPAN interface")},
        { 260, ("OtnOdu", "OTN Optical Data Unit")},
        { 261, ("OtnOtu", "OTN Optical channel Transport Unit")},
        { 262, ("IfVfiType", "VPLS Forwarding Instance Interface Type")},
        { 263, ("G9981", "G.998.1 bonded interface")},
        { 264, ("G9982", "G.998.2 bonded interface")},
        { 265, ("G9983", "G.998.3 bonded interface")},
        { 266, ("AluEpon", "Ethernet Passive Optical Networks (E-PON)")},
        { 267, ("AluEponOnu", "EPON Optical Network Unit")},
        { 268, ("AluEponPhysicalUni", "EPON physical User to Network interface")},
        { 269, ("AluEponLogicalLink", "The emulation of a point-to-point link over the EPON layer")},
        { 270, ("AluGponOnu", "GPON Optical Network Unit")},
        { 271, ("AluGponPhysicalUni", "GPON physical User to Network interface")},
        { 272, ("VmwareNicTeam", "VMware NIC Team")},
        { 277, ("DocsOfdmDownstream", "CATV Downstream OFDM interface")},
        { 278, ("DocsOfdmaUpstream", "CATV Upstream OFDMA interface")},
        { 279, ("Gfast", "G.fast port")},
        { 280, ("Sdci", "SDCI (IO-Link)")},
        { 281, ("XboxWireless", "Xbox wireless")},
        { 282, ("Fastdsl", "FastDSL")},
        { 283, ("DocsCableScte55d1FwdOob", "Cable SCTE 55-1 OOB Forward Channel")},
        { 284, ("DocsCableScte55d1RetOob", "Cable SCTE 55-1 OOB Return Channel")},
        { 285, ("DocsCableScte55d2DsOob", "Cable SCTE 55-2 OOB Downstream Channel")},
        { 286, ("DocsCableScte55d2UsOob", "Cable SCTE 55-2 OOB Upstream Channel")},
        { 287, ("DocsCableNdf", "Cable Narrowband Digital Forward")},
        { 288, ("DocsCableNdr", "Cable Narrowband Digital Return")},
        { 289, ("Ptm", "Packet Transfer Mode")},
        { 290, ("Ghn", "G.hn port")},
        { 291, ("OtnOtsi", "Optical Tributary Signal")},
        { 292, ("OtnOtuc", "OTN OTUCn")},
        { 293, ("OtnOduc", "OTN ODUC")},
        { 294, ("OtnOtsig", "OTN OTUC Signal")},
        { 295, ("MicrowaveCarrierTermination", "Air interface of a single microwave carrier")},
        { 296, ("MicrowaveRadioLinkTerminal", "Radio link interface for one or several aggregated microwave carriers")},
        { 297, ("Ieee8021axDrni", "IEEE 802.1AX Distributed Resilient Network Interface")},
        { 298, ("Ax25", "AX.25 network interfaces")},
        { 299, ("Ieee19061nanocom", "Nanoscale and Molecular Communication")},
        { 300, ("Cpri", "Common Public Radio Interface")},
        { 301, ("Omni", "Overlay Multilink Network Interface (OMNI)")},
        { 302, ("Roe", "Radio over Ethernet Interface")},
        { 303, ("P2pOverLan", "Point to Point over LAN interface")},
    };
}