using System.Text;

using ITPIE.Database.Generators.Model;

namespace ITPIE.Database.Generators;

public sealed partial class DatabaseCommandGenerator
{
    internal sealed class ValidatorEmitter
    {
        private readonly StringBuilder _builder = new(1024);

        public string Emit(DatabaseCommandClass c)
        {
            _builder.Clear();
            _builder.AppendLine("// <auto-generated/>");
            _builder.AppendLine("#nullable enable");

            GenerateClass(c);

            return _builder.ToString();
        }

        private void GenerateClass(DatabaseCommandClass c)
        {
            string indent = "";

            #region Namespace

            //
            // namespace N
            // {
            // }
            //

            if (!string.IsNullOrWhiteSpace(c.Namespace))
            {
                _builder.AppendLine($"namespace {c.Namespace}");
                _builder.AppendLine("{");

                indent += "    ";
            }

            #region Parents

            //
            // public partial static class C1
            // {
            //     public partial static class C2
            //     {
            //     }
            // }
            //

            // find outer-most parent
            DatabaseCommandClass? parent = c.Parent;
            List<string> parents = [];
            while (parent is not null)
            {
                parents.Add($"{parent.Modifiers} {parent.Keyword} {parent.Name}");
                parent = parent.Parent;
            }

            // write parents, starting with the outer-most
            for (int i = parents.Count - 1; i >= 0; i--)
            {
                _builder.AppendLine($"{indent}{parents[i]}");
                _builder.AppendLine($"{indent}{{");

                indent += "    ";
            }

            #region Class

            //
            // public static partial class C
            // {
            // }
            //

            _builder.AppendLine($"{indent}{c.Modifiers} {c.Keyword} {c.Name}");
            _builder.AppendLine($"{indent}{{");

            foreach (DatabaseCommandMethod m in c.Methods)
            {
                if (m.HasErrors)
                {
                    continue;
                }

                GenerateMethod(m, indent);
            }

            _builder.AppendLine($"{indent}}}");

            #endregion

            parent = c.Parent;
            while (parent is not null)
            {
                indent = new(' ', indent.Length - 4);

                _builder.AppendLine($"{indent}}}");

                parent = parent.Parent;
            }

            #endregion

            if (!string.IsNullOrWhiteSpace(c.Namespace))
            {
                _builder.AppendLine("}");
            }

            #endregion
        }

        private void GenerateMethod(DatabaseCommandMethod m, string indent)
        {
            indent += "    ";

            #region Preprocessor directive

            _builder.AppendLine("#if DEBUG");

            #region Method attributes

            _builder.AppendLine($"{indent}[{GeneratedCodeAttribute}]");
            _builder.AppendLine(
                $"{indent}[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Security\", \"CA2100: Review SQL queries for security vulnerabilities\", Justification = \"<Pending>\")]"
            );
            _builder.AppendLine($"{indent}[global::System.Diagnostics.DebuggerNonUserCode]");
            _builder.AppendLine(
                $"{indent}[global::ITPIE.Database.Abstractions.Testing.DatabaseCommandValidatorAttribute]"
            );

            #endregion

            #region Method signature

            _builder.AppendLine(
                $"{indent}internal static async global::System.Threading.Tasks.Task __Validate__{m.Name}("
            );
            _builder.AppendLine($"{indent}    global::Npgsql.NpgsqlConnection connection,");
            _builder.AppendLine($"{indent}    global::System.Threading.CancellationToken cancellationToken");
            _builder.AppendLine($"{indent})");
            _builder.AppendLine($"{indent}{{");

            #endregion

            #region Method implementation

            #region Command text

            //
            //     const string commandText = """
            // -- validate: N.C.M
            // SELECT id, name, created FROM widgets
            //
            // """;
            //

            _builder.AppendLine($"{indent}    const string commandText = \"\"\"");
            _builder.AppendLine($"-- validate: {m.FullyQualifiedIdentifier}");
            _builder.AppendLine(m.CommandText.Value);
            _builder.AppendLine("\"\"\";");

            #endregion

            #region Bind parameter validation & schema retrieval

            //
            // PostgreSQL must execute a statement to check that the bind parameters are valid, confirming the count
            // and compatible types. We avoid reading any fields off the Npgsql data reader, because we're not
            // gauranteed to have any rows.
            //
            //     * Default bind parameter values might filter out rows
            //     * The database is likely to be empty, so SELECT is unlikely to return any rows
            //

            if (m.BindParameters.Count == 0)
            {
                _builder.AppendLine(
                    $"{indent}    var columns = await global::ITPIE.Database.Abstractions.Testing.DatabaseCommandValidatorExtensions.ValidateAsync(connection, commandText, [], cancellationToken);"
                );
            }
            else
            {
                _builder.AppendLine(
                    $"{indent}    var columns = await global::ITPIE.Database.Abstractions.Testing.DatabaseCommandValidatorExtensions.ValidateAsync(connection, commandText, ["
                );

                foreach (DatabaseCommandBindParameter p in m.BindParameters)
                {
                    _builder.AppendLine(
                        $"{indent}        new global::Npgsql.NpgsqlParameter<{p.Type}>() {{ TypedValue = {(p.IsCollection ? $"[{p.ValidateDefaultValue}]" : p.ValidateDefaultValue)} }},"
                    );
                }

                _builder.AppendLine($"{indent}    ], cancellationToken);");
            }

            #endregion

            #region Row description validation

            //
            // From the row description, we can create a synthetic SELECT statement with default values (NOT NULL) for
            // each of the column types. This allows us to test Npgsql data reader field type mapping with guaranteed
            // row & column data.
            //

            if (m.Result.Parameters.Count == 0)
            {
                _builder.AppendLine(
                    $"{indent}    var validationContext = new global::ITPIE.Database.Abstractions.Testing.DatabaseCommandValidationContext(columns, new global::System.Collections.Generic.List<global::ITPIE.Database.Abstractions.Testing.DatabaseCommandValidationProperty>().AsReadOnly());"
                );
            }
            else
            {
                _builder.AppendLine(
                    $"{indent}    var validationContext = new global::ITPIE.Database.Abstractions.Testing.DatabaseCommandValidationContext(columns, new global::System.Collections.Generic.List<global::ITPIE.Database.Abstractions.Testing.DatabaseCommandValidationProperty>()"
                );
                _builder.AppendLine($"{indent}    {{");
                for (int i = 0; i < m.Result.Parameters.Count; i++)
                {
                    DatabaseCommandResultParameter p = m.Result.Parameters[i];
                    _builder.AppendLine(
                        $"{indent}        new global::ITPIE.Database.Abstractions.Testing.DatabaseCommandValidationProperty(\"{p.Name}\", {p.HasNullableAnnotation.ToString().ToLower()}),"
                    );
                }

                _builder.AppendLine($"{indent}    }}.AsReadOnly());");
            }

            _builder.AppendLine($"{indent}    validationContext.Validate();");
            _builder.AppendLine($"{indent}    var validateCommandText = validationContext.GetValidationCommandText();");

            //
            // Now we come to the part where we execute that validation command and test Npgsql data reader field type
            // mapping... this should uncover any PostgreSQL <=> C# type mistmatches.
            //

            _builder.AppendLine(
                $"{indent}    await using (var transaction = await connection.BeginTransactionAsync(cancellationToken))"
            );
            _builder.AppendLine(
                $"{indent}    await using (var command = new global::Npgsql.NpgsqlCommand(validateCommandText, connection))"
            );
            _builder.AppendLine(
                $"{indent}    await using (var reader = await command.ExecuteReaderAsync(cancellationToken))"
            );
            _builder.AppendLine($"{indent}    {{");
            _builder.AppendLine($"{indent}        while (await reader.ReadAsync(cancellationToken))");
            _builder.AppendLine($"{indent}        {{");
            for (int i = 0; i < m.Result.Parameters.Count; i++)
            {
                DatabaseCommandResultParameter p = m.Result.Parameters[i];
                if (p.IsReferenceType && p.HasNullableAnnotation)
                {
                    _builder.AppendLine(
                        $"{indent}            var field{i} = await reader.IsDBNullAsync({i}, cancellationToken) ? null : await reader.GetFieldValueAsync<{p.Type}>({i}, cancellationToken);"
                    );
                }
                else
                {
                    _builder.AppendLine(
                        $"{indent}            var field{i} = await reader.GetFieldValueAsync<{p.Type}>({i}, cancellationToken);"
                    );
                }
            }

            _builder.AppendLine($"{indent}        }}");
            _builder.AppendLine($"{indent}    }}");

            #endregion

            _builder.AppendLine($"{indent}}}");

            #endregion

            _builder.AppendLine("#endif");

            #endregion
        }
    }
}