using System.Text;

using ITPIE.Database.Generators.Model;

using Microsoft.CodeAnalysis.CSharp;

namespace ITPIE.Database.Generators;

public sealed partial class DatabaseCommandGenerator
{
    internal sealed class Emitter
    {
        private readonly StringBuilder _builder = new(1024);

        public string Emit(DatabaseCommandClass c)
        {
            _builder.Clear();
            _builder.AppendLine("// <auto-generated/>");
            _builder.AppendLine("#nullable enable");

            GenerateClass(c);

            return _builder.ToString();
        }

        private void GenerateClass(DatabaseCommandClass c)
        {
            string indent = "";

            #region Namespace

            //
            // namespace N
            // {
            // }
            //

            if (!string.IsNullOrWhiteSpace(c.Namespace))
            {
                _builder.AppendLine($"namespace {c.Namespace}");
                _builder.AppendLine("{");

                indent += "    ";
            }

            #region Parents

            //
            // public partial static class C1
            // {
            //     public partial static class C2
            //     {
            //     }
            // }
            //

            // find outer-most parent
            DatabaseCommandClass? parent = c.Parent;
            List<string> parents = [];
            while (parent is not null)
            {
                parents.Add($"{parent.Modifiers} {parent.Keyword} {parent.Name}");
                parent = parent.Parent;
            }

            // write parents, starting with the outer-most
            for (int i = parents.Count - 1; i >= 0; i--)
            {
                _builder.AppendLine($"{indent}{parents[i]}");
                _builder.AppendLine($"{indent}{{");

                indent += "    ";
            }

            #region Class

            //
            // public static partial class C
            // {
            // }
            //

            _builder.AppendLine($"{indent}{c.Modifiers} {c.Keyword} {c.Name}");
            _builder.AppendLine($"{indent}{{");

            foreach (DatabaseCommandMethod m in c.Methods)
            {
                if (m.HasErrors)
                {
                    continue;
                }

                GenerateSortKeys(m, indent);
                GenerateMethod(m, indent);
            }

            _builder.AppendLine($"{indent}}}");

            parent = c.Parent;
            while (parent is not null)
            {
                indent = new(' ', indent.Length - 4);

                _builder.AppendLine($"{indent}}}");

                parent = parent.Parent;
            }

            if (!string.IsNullOrWhiteSpace(c.Namespace))
            {
                _builder.AppendLine("}");
            }

            #endregion

            #endregion

            #endregion
        }

        private void GenerateSortKeys(DatabaseCommandMethod m, string indent)
        {
            if (m.SortableColumns.Count == 0)
            {
                return;
            }

            //
            // public static readonly IReadOnlySet<string> {Method}SortKeys = new HashSet<string>(...) { "device", ... };
            //
            // The declared [SortableBy] keys, for UI sort allowlists — sourcing an allowlist here
            // means it cannot drift from the generated command-text variants.
            //

            _builder.AppendLine($"{indent}    [{GeneratedCodeAttribute}]");
            _builder.Append(
                $"{indent}    public static readonly global::System.Collections.Generic.IReadOnlySet<string> {m.Name}SortKeys = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal) {{ "
            );

            for (int i = 0; i < m.SortableColumns.Count; i++)
            {
                if (i != 0)
                {
                    _builder.Append(", ");
                }

                _builder.Append(SymbolDisplay.FormatLiteral(m.SortableColumns[i].Key, quote: true));
            }

            _builder.AppendLine(" };");
        }

        private void GenerateMethod(DatabaseCommandMethod m, string indent)
        {
            indent += "    ";

            string connection = GetConnectionName(m);
            string cancellationToken = GetCancellationTokenName(m);

            #region Method attributes

            //
            // [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ITPIE.Database.Generators", "0.0.0.0")]
            // [global::System.Diagnostics.DebuggerNonUserCode]
            //

            _builder.AppendLine($"{indent}[{GeneratedCodeAttribute}]");
            _builder.AppendLine($"{indent}[global::System.Diagnostics.DebuggerNonUserCode]");

            #endregion

            #region Method signature

            //
            // public static partial async IAsyncEnumerable<(long Id, string Name, DateTimeOffset Created)> GetWidgets(
            //     global::Npgsql.NpgsqlConnection connection,
            //     global::System.Int64 id,
            //     [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken
            // )
            // {
            //     ...
            // }
            //

            string extension = m.IsExtensionMethod ? "this " : "";

            _builder.AppendLine($"{indent}{m.Modifiers} async {m.ReturnType} {m.Name}(");

            #region Method parameters

            foreach (DatabaseCommandMethodParameter p in m.Parameters)
            {
                if (p.IsConnection)
                {
                    _builder.AppendLine($"{indent}    {extension}{p.Type} {p.Name},");
                    continue;
                }

                if (p.IsCancellationToken)
                {
                    _builder.AppendLine(
                        $"{indent}    [global::System.Runtime.CompilerServices.EnumeratorCancellation] {p.Type} {p.Name}"
                    );
                    continue;
                }

                _builder.AppendLine($"{indent}    {p.Type} {p.Name},");
            }

            _builder.AppendLine($"{indent})");
            _builder.AppendLine($"{indent}{{");

            #endregion

            #endregion

            #region Method implementation

            #region Command text

            //
            //      const string __commandText = """
            //  -- N.C.M
            //  SELECT id, name, created from widgets
            //
            //  """;
            //
            // For a [SortableBy] method, one const per (column, direction) variant is produced by
            // token substitution, and __commandText becomes a local selected from the 'sort'/'dir'
            // parameters. An unrecognized sort falls back to the first declared column; direction
            // is descending only when dir equals "desc" (case-insensitive).
            //

            if (m.SortableColumns.Count == 0)
            {
                _builder.AppendLine($"{indent}    const string __commandText = \"\"\"");
                _builder.AppendLine($"-- {m.FullyQualifiedIdentifier}");
                _builder.AppendLine(m.CommandText.Value);
                _builder.AppendLine("\"\"\";");
            }
            else
            {
                for (int i = 0; i < m.SortableColumns.Count; i++)
                {
                    (string key, string sqlExpression) = m.SortableColumns[i];

                    foreach (bool descending in new[] { false, true })
                    {
                        string direction = descending ? "desc" : "asc";

                        _builder.AppendLine($"{indent}    const string __commandText_{i}_{direction} = \"\"\"");
                        _builder.AppendLine($"-- {m.FullyQualifiedIdentifier} [sort={key} {direction}]");
                        _builder.AppendLine(SubstituteSortTokens(m.CommandText.Value, sqlExpression, descending));
                        _builder.AppendLine("\"\"\";");
                    }
                }

                _builder.AppendLine(
                    $"{indent}    bool __descending = string.Equals(dir, \"desc\", global::System.StringComparison.OrdinalIgnoreCase);"
                );
                _builder.AppendLine($"{indent}    string __commandText = (sort, __descending) switch");
                _builder.AppendLine($"{indent}    {{");

                for (int i = 0; i < m.SortableColumns.Count; i++)
                {
                    string keyLiteral = SymbolDisplay.FormatLiteral(m.SortableColumns[i].Key, quote: true);

                    _builder.AppendLine($"{indent}        ({keyLiteral}, false) => __commandText_{i}_asc,");
                    _builder.AppendLine($"{indent}        ({keyLiteral}, true) => __commandText_{i}_desc,");
                }

                _builder.AppendLine($"{indent}        (_, false) => __commandText_0_asc,");
                _builder.AppendLine($"{indent}        (_, true) => __commandText_0_desc,");
                _builder.AppendLine($"{indent}    }};");
            }

            #endregion

            #region Command

            //
            // await using var __command = new global::Npgsql.NpgsqlCommand(__commandText, connection);
            // __command.Parameters.Add(new global::Npgsql.NpgsqlParameter<global::System.Int64>() {{ TypedValue = id }});
            //

            _builder.AppendLine(
                $"{indent}    await using var __command = new global::Npgsql.NpgsqlCommand(__commandText, {connection});"
            );

            #region Command parameters

            foreach (DatabaseCommandBindParameter p in m.BindParameters)
            {
                _builder.AppendLine(
                    $"{indent}    __command.Parameters.Add(new global::Npgsql.NpgsqlParameter<{p.Type}>() {{ TypedValue = {p.Name} }});"
                );
            }

            #endregion

            #endregion

            #region Reader

            //
            // return tuple:
            //
            // await using var __reader = await __command.ExecuteReaderAsync(cancellationToken);
            // while (await __reader.ReadAsync(cancellationToken))
            // {
            //     var __field0 = await __reader.GetFieldValueAsync<global::System.Int64>(0, cancellationToken);
            //     var __field1 = await __reader.GetFieldValueAsync<global::System.String>(1, cancellationToken);
            //     var __field2 = await __reader.GetFieldValueAsync<global::System.DateTimeOffset>(2, cancellationToken);
            //     yield return ...;
            // }
            //

            _builder.AppendLine(
                $"{indent}    await using var __reader = await __command.ExecuteReaderAsync({cancellationToken});"
            );
            _builder.AppendLine($"{indent}    while (await __reader.ReadAsync({cancellationToken}))");
            _builder.AppendLine($"{indent}    {{");

            #region Fields

            for (int i = 0; i < m.Result.Parameters.Count; i++)
            {
                DatabaseCommandResultParameter p = m.Result.Parameters[i];
                if (p.IsReferenceType && p.HasNullableAnnotation)
                {
                    _builder.AppendLine(
                        $"{indent}        var __field{i} = await __reader.IsDBNullAsync({i}, {cancellationToken}) ? null : await __reader.GetFieldValueAsync<{p.Type}>({i}, {cancellationToken});"
                    );
                }
                else
                {
                    _builder.AppendLine(
                        $"{indent}        var __field{i} = await __reader.GetFieldValueAsync<{p.Type}>({i}, {cancellationToken});"
                    );
                }
            }

            #endregion

            #region Return

            //
            // single field:
            //
            // yield return __field0;
            //
            // value tuple 1-field:
            //
            // yield return new ValueTuple<T1>(__field0);
            //
            // value tuple:
            //
            // yield return (__field0, __field1, __field2);
            //
            // ctor:
            //
            // yield return new WidgetRow(__field0, __field1, __field2);
            //

            if (m.Result.IsSingleField)
            {
                _builder.Append($"{indent}        yield return ");
            }
            else if (m.Result.IsValueTuple)
            {
                if (m.Result.Parameters.Count == 1)
                {
                    _builder.Append(
                        $"{indent}        yield return new global::System.ValueTuple<{m.Result.Parameters[0].Type}>("
                    );
                }
                else
                {
                    _builder.Append($"{indent}        yield return (");
                }
            }
            else
            {
                _builder.Append($"{indent}        yield return new {m.Result.Type}(");
            }

            for (int i = 0; i < m.Result.Parameters.Count; i++)
            {
                if (i != 0)
                {
                    _builder.Append(", ");
                }

                _builder.Append($"__field{i}");
            }

            if (m.Result.IsSingleField)
            {
                _builder.AppendLine(";");
            }
            else
            {
                _builder.AppendLine(");");
            }

            #endregion

            _builder.AppendLine($"{indent}    }}");

            #endregion

            _builder.AppendLine($"{indent}}}");

            #endregion
        }

        private static string GetConnectionName(DatabaseCommandMethod m)
        {
            string name = "";
            foreach (DatabaseCommandMethodParameter p in m.Parameters)
            {
                if (p.IsConnection)
                {
                    name = p.Name;
                    break;
                }
            }

            return name;
        }

        private static string GetCancellationTokenName(DatabaseCommandMethod m)
        {
            string name = "";
            foreach (DatabaseCommandMethodParameter p in m.Parameters)
            {
                if (p.IsCancellationToken)
                {
                    name = p.Name;
                    break;
                }
            }

            return name;
        }
    }
}